"""
exporters.py
-----

This file contains functions that convert and export raw information into file outputs.
"""

import csv  # To save the followers table to CSV
import json  # To save the followers table to JSON

from datetime import datetime
from typing import Any  # To help return hints

def md_header() -> str:
    # Makes the header for the top of the markdown file
    # This does not require any variables passed
    return """
# devtkit  \n
> Generated by [devtkit](https://github.com/tyleruploads/devtkit).
> It is not limited to Markdown files; it supports Markdown, JSON, and CSV exports
"""

def md_profile_header(user_info: dict[str, Any]) -> str:
    return (
        f"### Profile: {user_info['name']}\n\n"
        f"| Attribute | Details |\n"
        f"| :--- | :--- |\n"
        f"| **Name** | {user_info['name']} |\n"

        f"| **Username** | [{user_info['username']}]"
        f"(https://dev.to/{user_info['username']}) |\n"

        f"| Summary | {user_info['summary']} |\n"
        f"| Location | {user_info['location']} |\n"
        f"| Joined At | {user_info['joined_at']} |\n"

        f"| User ID | [{user_info['id']}]"
        f"(https://dev.to/api/users/{user_info['id']}) |\n"

        f"| **Profile Picture** | <img src='{user_info['profile_image']}' width='100' alt='Profile'>  |\n"
    )

def md_info_block(followers_list: list[dict]) -> str:
    # This makes a block to put in the Markdown output
    # This block contains information such as the date and follower count

    # Get the time
    now = datetime.now()
    # Example: Thursday, June 18, 2026
    formatted_date = now.strftime("%A, %B %d, %Y")

    # Get follower count
    follower_count = len(followers_list)

    return (
        f"> This was generated on {formatted_date}  \n"
        f"> {follower_count} followers were found  \n\n"
    )

def md_profiles_table(followers_list: list[dict]) -> str:
    # Check if the user has no followers
    if len(followers_list) == 0:
        # Return a notice that there are no followers
        return (
            "> NOTICE: The user that the provided API Key"
            "belongs to does not appear to have any followers"
            "There are no followers to make a table with"
        )

        # End of if statement

    users_md_part = """
| Index | Username | Name | Followed At | User ID |
| :--- | :--- | :--- | :--- | :--- |
"""

    for idx, follower in enumerate(followers_list):
        # Define variables
        name = follower["name"]
        username = follower["username"]
        user_id = follower["user_id"]

        # created_at is follow time, not account creation time
        followed_at = follower["created_at"]

        user_md_part = (
            f"| {idx} | [@{username}](https://dev.to/{username}) | {name} |"
            f"{followed_at} | [{user_id}](https://dev.to/api/users/{user_id}) |  \n"
        )
        users_md_part += user_md_part

    return users_md_part

def md_make(followers_list: list[dict], self_info: dict[str, Any]) -> str:
    md_string = ""
    md_string += md_header()
    md_string += md_profile_header(self_info)
    md_string += md_info_block(followers_list)
    md_string += md_profiles_table(followers_list)
    return md_string

def save_files(followers_list: list[dict], formats_and_paths: dict[str, str], self_info: dict[str, Any]=None) -> None:
    for mode, path in formats_and_paths.items():
        if mode == "markdown":
            with open(path, "w") as f:
                f.write(md_make(followers_list, self_info))

            print(f"Saved in the Markdown file format to {path}")
        elif mode == "json":
            with open(path, "w") as f:
                json.dump(followers_list, f, indent=4)

            print(f"Saved in the JSON file format to {path}")
        elif mode == "csv":
            headers = followers_list[0].keys()

            with open(path, "w", newline="", encoding="utf-8") as f:
                writer = csv.DictWriter(f, fieldnames=headers)

                writer.writeheader()
                writer.writerows(followers_list)

            print(f"Saved in the CSV file format to {path}")
        else:
            raise ValueError(
                f"The mode value of {mode} is not supported"
                "in the save_followers_table function.",
            )
